//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesAPI.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeesAPI.Domain.Resources.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM public.&quot;Departments&quot; WHERE Id = @Id;.
        /// </summary>
        internal static string DepartmentDelete {
            get {
                return ResourceManager.GetString("DepartmentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;Departments&quot; (DepartmentName, DepartmentPhone) VALUES (@DepartmentName, @DepartmentPhone) RETURNING Id;.
        /// </summary>
        internal static string DepartmentInsert {
            get {
                return ResourceManager.GetString("DepartmentInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM public.&quot;Departments&quot; WHERE DepartmentName = @DepartmentName;.
        /// </summary>
        internal static string DepartmentReadByName {
            get {
                return ResourceManager.GetString("DepartmentReadByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE public.&quot;Departments&quot; SET DepartmentName = CASE WHEN @DepartmentName IS NULL THEN DepartmentName ELSE @DepartmentName END, DepartmentPhone = CASE WHEN @DepartmentPhone IS NULL THEN DepartmentPhone ELSE @DepartmentPhone END WHERE Id = @Id;.
        /// </summary>
        internal static string DepartmentUpdate {
            get {
                return ResourceManager.GetString("DepartmentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM public.&quot;Employees&quot; WHERE Id = @Id;.
        /// </summary>
        internal static string EmployeeDelete {
            get {
                return ResourceManager.GetString("EmployeeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT empl.Id, empl.Name, empl.Surname, empl.Phone, empl.CompanyId, requiredPass.Type, requiredPass.Number, requiredDep.DepartmentName, requiredDep.DepartmentPhone FROM public.&quot;Employees&quot; empl JOIN public.&quot;Departments&quot; requiredDep ON requiredDep.Id = empl.DepartmentId JOIN public.&quot;Passports&quot; requiredPass ON requiredPass.Id = empl.PassportId WHERE empl.CompanyId = @Id;.
        /// </summary>
        internal static string EmployeeGetAllByCompanyId {
            get {
                return ResourceManager.GetString("EmployeeGetAllByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT empl.Id, empl.Name, empl.Surname, empl.Phone, empl.CompanyId, requiredPass.Type, requiredPass.Number, requiredDep.DepartmentName, requiredDep.DepartmentPhone FROM public.&quot;Employees&quot; empl JOIN public.&quot;Departments&quot; requiredDep ON requiredDep.Id = empl.DepartmentId JOIN public.&quot;Passports&quot; requiredPass ON requiredPass.Id = empl.PassportId WHERE requiredDep.DepartmentName = @depname;.
        /// </summary>
        internal static string EmployeeGetAllByDepartmentName {
            get {
                return ResourceManager.GetString("EmployeeGetAllByDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DepartmentId FROM public.&quot;Employees&quot; WHERE Id = @Id;.
        /// </summary>
        internal static string EmployeeGetDepartmentId {
            get {
                return ResourceManager.GetString("EmployeeGetDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PassportId FROM public.&quot;Employees&quot; WHERE Id = @Id;.
        /// </summary>
        internal static string EmployeeGetPassportId {
            get {
                return ResourceManager.GetString("EmployeeGetPassportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;Employees&quot; (Name, Surname, Phone, CompanyId, PassportId, DepartmentId) VALUES (@Name, @Surname, @Phone, @CompanyId, @PassportId, @DepartmentId) RETURNING Id;.
        /// </summary>
        internal static string EmployeeInsert {
            get {
                return ResourceManager.GetString("EmployeeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM public.&quot;Employees&quot; WHERE Id = @Id;.
        /// </summary>
        internal static string EmployeeRead {
            get {
                return ResourceManager.GetString("EmployeeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE public.&quot;Employees&quot; SET Name = CASE WHEN @Name IS NULL THEN Name ELSE @Name END, Surname = CASE WHEN @Surname IS NULL THEN Surname ELSE @Surname END, Phone = CASE WHEN @Phone IS NULL THEN Phone ELSE @Phone END WHERE Id = @Id;.
        /// </summary>
        internal static string EmployeeUpdate {
            get {
                return ResourceManager.GetString("EmployeeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM public.&quot;Passports&quot; WHERE Id = @Id;.
        /// </summary>
        internal static string PassportDelete {
            get {
                return ResourceManager.GetString("PassportDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;Passports&quot; (Type, Number) VALUES (@Type, @Number) RETURNING id;.
        /// </summary>
        internal static string PassportInsert {
            get {
                return ResourceManager.GetString("PassportInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM public.&quot;Passports&quot; WHERE Number = @Number;.
        /// </summary>
        internal static string PassportReadByNum {
            get {
                return ResourceManager.GetString("PassportReadByNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE public.&quot;Passports&quot; SET Number = CASE WHEN @Number IS NULL THEN Number ELSE @Number END, Type = CASE WHEN @Type IS NULL THEN Type ELSE @Type END WHERE Id = @Id;.
        /// </summary>
        internal static string PassportUpdate {
            get {
                return ResourceManager.GetString("PassportUpdate", resourceCulture);
            }
        }
    }
}
